### ISSUE TITLE
Time zones in timestamp columns break in MySQL 5 Strict Mode

### ISSUE THREAD

**Issue by dmingos** [jpfuentes2/php-activerecord#197]
If MySQL 5.0 is in strict mode, the ' T' in the datetime format, 'Y-m-d H:i:s T' causes MySQL to throw a critical error and the insert/update is aborted.

I haven't tested this but I am assuming it is a problem in Column.php and Model.php as well as Connection.php.

**Comment by shawnpyle** [comment]
[A solution found in the forums](http://www.phpactiverecord.org/boards/4/topics/531-saving-date-to-mysql-problem) uses `ActiveRecord\Connection::$datetime_format = 'Y-m-d H:i:s';`.
