### ISSUE TITLE
Model::delete and Model::update

### ISSUE THREAD

**Issue by outring** [jpfuentes2/php-activerecord#24]
It very useful to have these static methods for removing or updating bunch of records without selecting them. For example:
    Post::delete(array(
        'conditions' => array('`user_id` = ?', $user->id), 'limit' => 5
    ))

```
Post::update(array(
    'conditions' => array('`user_id` = ?', $user->id),
    'set' => array('`views_count` = `views_count` + 1, `last_viewer` = ?', $user->id)
))
```

**Comment by Lusitaniae** [comment]
Hi @jpfuentes2, Shouldn't update_all method be referred to in this section instead of update? 
http://www.phpactiverecord.org/projects/main/wiki/Basic_CRUD#massive

**Comment by SailingGoat** [comment]
update() and delete() are being called on Table there. Which is different
than calling Model::update_all(). I would imagine that both should work.
