### ISSUE TITLE
Mass serialization ($all->to_json())

### ISSUE THREAD

**Issue by nguyenbathanh** [jpfuentes2/php-activerecord#385]
I hope we can convert a list of objects to json format or an array. Example:

    $all = Person::all();
    $json = $all->to_json();

or

    $array = $all->to_array();

I speak English not well, so sorry for that.

**Comment by daniel-aranda** [comment]
I understand the performance implications that involve to make this a PHPActiveRecord core feature. I just want to share the workaround that I have applied on my PHPActiveRecord projects. 

First of all, my models extends my "own" model abstract, which also extends the original PHPActiveRecord Model. Then, there I have a "helper" function:

```php
<?php
abstract class DanielArandaModelAbstract extends ActiveRecord\Model{

    public function collection_to_array(){
        $results = call_user_func_array([get_class($this), 'all'], func_get_args());

        if( is_array($results) ){

            $results = array_map(function($item){
                return $item->to_array();
            }, $results);

            return $results;

        }else{
            return [$results->to_array()];
        }

    }

}
```

Then, in your project you only need this:
```php
var_dump(YourModel::collection_to_array());
```

You will get the result of "all" converted into raw array.

It also forward the arguments for all, so you use it like all with the plus that it returns raw array instead of objects. And you are not doing foreach or maps around your project.

Bests,

**Comment by koenpunt** [comment]
You'd probably want to define your function as `static`. 
And instead of using `get_class($this)` you're better of using "late static bindings"' `get_called_class()`:
```php
$results = call_user_func_array([get_called_class(), 'all'], func_get_args());

**Comment by koenpunt** [comment]
And it's better to not pass them by reference:

```php
$called_class = get_called_class();
$args = func_get_args();
$results = call_user_func_array([$called_class, 'all'], $args);

**Comment by daniel-aranda** [comment]
I already refactor it a bit also:

```php
<?php

namespace App\Models;

abstract class ModelAbstract extends \ActiveRecord\Model{

    public static function collection_to_array(){
        $results = call_user_func_array('static::all', func_get_args());

        if( is_array($results) ){

            $results = array_map(function($item){
                return $item->to_array();
            }, $results);

            return $results;

        }else{
            return [$results->to_array()];
        }

    }

}
```

BTW get_called_class is not needed as static refer to current class, and is how source code of PHPActiveRecord also does with all as wrapper to find.

**Comment by koenpunt** [comment]
Is there a case that `Model::all` doesn't return an array ?

**Comment by daniel-aranda** [comment]
Fair point, in theory not, but if you remember ["all"](https://github.com/jpfuentes2/php-activerecord/blob/master/lib/Model.php#L1435) is a proxy to find, thought that someone could call all with one argument, which will be ending using [find_by_pk](https://github.com/jpfuentes2/php-activerecord/blob/master/lib/Model.php#L1606).


I have seen people doing:
```php
Model::all(1);
```

It is a programmer "issue" as it is wrong implementation of all; we want our workaround code to be homogeneous with the native behavior. In strict mode, I would say that in my own project I would throw an Exception if programmer attempts to use "all" as finder by pk.

**Comment by koenpunt** [comment]
`Model::all(1)` will never return as single object.

https://github.com/jpfuentes2/php-activerecord/blob/master/lib/Model.php#L1579

**Comment by daniel-aranda** [comment]
@koenpunt  $single is not used, please double check the line, it proxy to find_by_pk and ignore the var $single:
https://github.com/jpfuentes2/php-activerecord/blob/master/lib/Model.php#L1606

I also confirmed the behavior with Unit Test:
```php
public function testIsArray(){
    $this->assertFalse( is_array(SomeModel::all(1)) );
    $this->assertTrue( is_array(SomeModel::all()) );
}
```
;)

**Comment by koenpunt** [comment]
Oh well, that's pretty ugly. An obvious bug if you ask me.

**Comment by daniel-aranda** [comment]
Right! Thank You for create the issue. Please mention me when the PR is ready and I would love to collaborate in the code review.
