### ISSUE TITLE
Opened IRC channel #php-activerecord

### ISSUE THREAD

**Issue by koenpunt** [jpfuentes2/php-activerecord#434]
@shmax asked me for IM, which I also sometimes prefer over the passive conversations there are here on Github, so I did setup a IRC channel on irc.freenode.net; `#php-activerecord`

**Comment by cvanschalkwijk** [comment]
@koenpunt  How about we use https://gitter.im/

**Comment by jpfuentes2** [comment]
I actively use IRC. I think that's more appropriate. I'm going to start idling there.

**Comment by cvanschalkwijk** [comment]
I just think something like glitter for chat would be better.  It stores history, is a web client, has a mobile app, and uses github for SSO as opposed to IRC and having to install a client.
