### ISSUE TITLE
When a foriegn key is NULL and it's value is mapped with belongs_to, serialization breaks

### ISSUE THREAD

**Issue by lfglopes** [jpfuentes2/php-activerecord#476]
Let's say

    static $belongs_to = array(
            'category' => array('category', 'class_name' => 'Category')
    );

    $obj->category // is null

    $obj->to_json(array('include' => array('category'))); // breaks:

Catchable fatal error:  Argument 1 passed to ActiveRecord\Serialization::__construct() must be an instance of ActiveRecord\Model, null given, called in vendor/activerecord/lib/Serialization.php on line 178 and defined in <b>vendor/activerecord/lib/Serialization.php on line 96

**Comment by lfglopes** [comment]
guess you can close this now.. :)

**Comment by jpfuentes2** [comment]
Thanks :)
