### ISSUE TITLE
web site is down?

### ISSUE THREAD

**Issue by brtriver** [jpfuentes2/php-activerecord#507]
web site (http://www.phpactiverecord.org/) is currently down.
It seems that this domain expired.

**Comment by saruhei** [comment]
I use php-activerecord in my product.
So I am very troubled.

Please revival web site ASAP!

**Comment by S-anasol** [comment]
=(

**Comment by fventurini** [comment]
love phpactiverecord me too

**Comment by jpfuentes2** [comment]
Sorry, everyone! This seems to happen every year and I usually have no excuse. This time I've been CRAZY busy.

**Comment by jpfuentes2** [comment]
.com is working and .org should follow suit soon. Thanks everyone.

**Comment by CC007** [comment]
The website seems to be down again.

**Comment by thewhit** [comment]
@CC007 a copy of the site is available https://phpactiverecord.xyz

**Comment by Flexo013** [comment]
The copy and the original are both down.

**Comment by thewhit** [comment]
> The copy and the original are both down.

https://phpactiverecord.xyz is back online.
