### ISSUE TITLE
Help?  Multiple has many associations

### ISSUE THREAD

**Issue by jamesmstone** [jpfuentes2/php-activerecord#511]
I have a database setup with a `students` table. The `students` table has a one to many relationship with a few other tables. ie a student can have multiple subjects. but also a student can have multiple awards.

Here is the code:

	class student extends Model {
		static $table_name = 'students';
		static $primary_key = 'username';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $has_many = [
			[
				#'subjects', 'foreign_key' => 'studentUsername',
				['subjects', 'foreign_key' => 'studentUsername'],
				['academicAwards', 'foreign_key' => 'studentUsername'],
				['nonAcademicAwards', 'foreign_key' => 'studentUsername'],
				['sportParticipation', 'foreign_key' => 'studentUsername', 'class_name' => 'sportParticipation'],
				['leadershipPositions', 'foreign_key' => 'studentUsername'],
				['houseParticipation', 'foreign_key' => 'studentUsername', 'class_name' => 'houseParticipation']
			]
		];
	}

	class subject extends Model {
		static $table_name = 'studentSubjects';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $belongs_to = [
			['student']
		];
	}

	class academicAward extends Model {
		static $table_name = 'academicAwards';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $belongs_to = [
			['student']
		];
	}

	class nonAcademicAward extends Model {
		static $table_name = 'nonAcademicAwards';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $belongs_to = [
			['student']
		];
	}

	class sportParticipation extends Model {
		static $table_name = 'sportParticipation';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $belongs_to = [
			['student']
		];
	}

	class leadershipPosition extends Model {
		static $table_name = 'leadershipPositions';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $belongs_to = [
			['student']
		];
	}

	class houseParticipation extends Model {
		static $table_name = 'houseParticipation';
		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
		static $belongs_to = [
			['student']
		];

When I run the code as above,  I get the following error:

    Warning: trim() expects parameter 1 to be string, array given in vendor\php-activerecord\php-activerecord\lib\Inflector.php on line 116
    
    Notice: Uninitialized string offset: 0 in vendor\composer\ClassLoader.php on line 317
    
    Notice: Uninitialized string offset: 0 in vendor\composer\ClassLoader.php on line 349

If I have :

	

    class student extends Model {
    		static $table_name = 'students';
    		static $primary_key = 'username';
    		static $datetime_format = 'Y-m-d H:i:s'; // https://stackoverflow.com/questions/17222180/phpactiverecord-incorrect-datetimeformat
    		static $has_many = [
    			[
    				'subjects', 'foreign_key' => 'studentUsername',
    			]
    		];
    	}
It works fine, except it only works for the single relationship; `one student to many subjects`.

**Comment by visavi** [comment]
most likely you will need to specify the name of the class
```['subjects', 'foreign_key' => 'studentUsername', 'class_name' => 'YourClass']```

and that there were no such problems must be properly called a table and model

**Comment by jamesmstone** [comment]
Thanks for your quick reply?
did you mean like this?

	static $has_many = [
				[
					['subjects', 'foreign_key' => 'studentUsername', 'class_name' => 'subject'],
					['academicAwards', 'foreign_key' => 'studentUsername','class_name' => 'academicAward'],
					['nonAcademicAwards', 'foreign_key' => 'studentUsername','class_name' => 'nonAcademicAward'],
					['sportParticipation', 'foreign_key' => 'studentUsername', 'class_name' => 'sportParticipation'],
					['leadershipPositions', 'foreign_key' => 'studentUsername','class_name' => 'leadershipPosition'],
					['houseParticipation', 'foreign_key' => 'studentUsername', 'class_name' => 'houseParticipation']
				]
			];

Unfortunately that gives the same error

**Comment by jamesmstone** [comment]
Sorry I should also add the fatal error in both cases is: `Class \ does not exist`

**Comment by jamesmstone** [comment]
Thanks I have figured it out, I accidentally added an extra array
