### ISSUE TITLE
DateTime::__construct(): Failed to parse time string (2016-01-26 20:24:01 AWST) at position 20 (A): The timezone could not be found in the database

### ISSUE THREAD

**Issue by imadige** [jpfuentes2/php-activerecord#518]
File: .../jumbada.com/main/lib/activerecord/lib/Connection.php:482

472:         * @return DateTime
473:         */
474:        public function string_to_datetime($string)
475:        {
476:            $date = date_create($string);
477:            $errors = \DateTime::getLastErrors();
478:    
479:            if ($errors['warning_count'] > 0 || $errors['error_count'] > 0)
480:                return null;
481:    
482:            return new DateTime($date->format(static::$datetime_format));
483:        }
484:    
485:        /**
486:         * Adds a limit clause to the SQL query.

**Comment by koenpunt** [comment]
This is not a problem with AR, but with your php setup. Try googling on "The timezone could not be found in the database"
