### ISSUE TITLE
Uncaught ActiveRecord\DatabaseException: PDOException: SQLSTATE[HY000] [1049] Unknown database 'orders_test

### ISSUE THREAD

**Issue by Shun87** [jpfuentes2/php-activerecord#527]
When I run example orders, I got the error:Uncaught ActiveRecord\DatabaseException: PDOException: SQLSTATE[HY000] [1049] Unknown database 'orders_test

**Comment by visavi** [comment]
if you're not confused, and such a database does exist, try without underscore create a database
