### ISSUE TITLE
WWW.PHPACTIVERECORD.ORG DOWN (where can copy of docs be obtained?)

### ISSUE THREAD

**Issue by phestermcs** [jpfuentes2/php-activerecord#529]

**Comment by adonet** [comment]
:(

**Comment by wriver4** [comment]
A large part of the documentation is within the code. If that does not work for you and they are not up in several days I can put up an older copy of them.

**Comment by koenpunt** [comment]
Try Google cache for the time being

**Comment by benmcmath** [comment]
Site appears to be back online (and much faster IMHO).

I found yesterday that archive.org has a recent copy and there are tools to download a local copy of a archive.org snapshot.  That's what I did just incase it went down again.

**Comment by koenpunt** [comment]
@jpfuentes2 did you change anything? Or was this just a service interruption at the hosting provider?

**Comment by jpfuentes2** [comment]
@koenpunt yes, I did. The service was down and needed to be bounced. Sorry all :(
