### ISSUE TITLE
Docs is not available in www.phpactiverecord.org

### ISSUE THREAD

**Issue by salvatorelapi** [jpfuentes2/php-activerecord#536]
Where is docs now ?

**Comment by koenpunt** [comment]
@jpfuentes2 looks like the registration has expired?

**Comment by salvatorelapi** [comment]
yes expired today http://whois.domaintools.com/phpactiverecord.org . Can you resolve ?

**Comment by jpfuentes2** [comment]
Fixed. We should get these docs up on `gh-pages`.

**Comment by jpfuentes2** [comment]
They also need a huge update :(
