### ISSUE TITLE
N+1 Problem

### ISSUE THREAD

**Issue by Stormcore** [jpfuentes2/php-activerecord#552]
Need to have support of Eager Loading like in Ruby on Rails

**Comment by koenpunt** [comment]
Any more details for your request?

**Comment by Stormcore** [comment]
@koenpunt Hello, sure thing! Here it is:
https://www.sitepoint.com/silver-bullet-n1-problem/

**Comment by ShaneShipston** [comment]
Is this what you are looking for? [Eager Loading](http://www.phpactiverecord.org/projects/main/wiki/Finders#eager-loading)

**Comment by Stormcore** [comment]
@ShaneShipston thanks! Did not see in docs before
