### ISSUE TITLE
Model 'before_save' callback is not exist

### ISSUE THREAD

**Issue by aigdonia** [jpfuentes2/php-activerecord#559]
I found in the documentation that I can bind callback to `before_save` on a model, but it is obviously not there, I checked the `Model::save()` and can't find the callback binding there, to do so I need to bind the callback to both `before_create` and `before_update`.

I suggest adding the `before_save` and `after_save` as it support more generic model manipulation feature

**Comment by koenpunt** [comment]
That's already handled within the callback class: 
https://github.com/jpfuentes2/php-activerecord/blob/master/lib/CallBack.php#L176
