### ISSUE TITLE
Completion  in phpstorm

### ISSUE THREAD

**Issue by Keberdle** [jpfuentes2/php-activerecord#566]
Hi, is there a way to define entity properties to start completion properties in phpstorm?

**Comment by tendallas** [comment]
I think there is custom stub generation only could help you

**Comment by NanneHuiges** [comment]
You can just add the various properties in a phpdoc, e.g.


    /**
     * @property int      $id
     * @property string $name
     */
    class MyThing extends Model{}


This would give you completion, but it does mean you have to add these manually, which is sorta the thing you tried to avoid. You could quite easily write a script that will generate this from your database btw.

Completion of the magic methods is harder.

**Comment by Keberdle** [comment]
Works well, thank You HanneGuiges. This will reduce typing error and speedup code writing.
Must be added.
`
 /** @var \Db\Coupons $coupon */
 $coupon = \Db\Coupons::find($coupon_id);`
