### ISSUE TITLE
wrong connection details

### ISSUE THREAD

**Issue by fruitloop** [jpfuentes2/php-activerecord#569]
Hi from one moment to the other (no clue what I did) ActiveRecord won't connect to my Database.

I set the following connection string:
`pgsql://user:supersecurepassword@user-pgsql.services.easyname.eu/userdb1?charset=utf8`

Therefore the connection should go to `user-pgsql.services.easyname.eu` instead of `86.32.42.104` (the external ip of my local machine)

It also should use the user `user` instead of `roland` (again my local user)  
The only thing that seems to work is the name for the database `userdb1`.

what am I doing wrong?

it crashes with the following message:
```
Type: ActiveRecord\DatabaseException
Message: exception 'PDOException' with message 'SQLSTATE[08006] [7] FATAL: no pg_hba.conf entry for host "86.32.42.104", user "roland", database "userdb1", SSL on FATAL: no pg_hba.conf entry for host "86.32.42.104", user "roland", database "userdb1", SSL off' in /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Connection.php:249 Stack trace: #0 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Connection.php(249): PDO->__construct('pgsql:host=e365...', NULL, 'someLongihsPass...', Array) #1 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Connection.php(111): ActiveRecord\Connection->__construct(Object(stdClass)) #2 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/ConnectionManager.php(33): ActiveRecord\Connection::instance('pgsql://userd...') #3 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Table.php(103): ActiveRecord\ConnectionManager::get_connection(NULL) #4 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Table.php(80): ActiveRecord\Table->reestablish_connection(false) #5 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Table.php(61): ActiveRecord\Table->__construct('Article') #6 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Model.php(744): ActiveRecord\Table::load('Article') #7 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Model.php(1567): ActiveRecord\Model::table() #8 [internal function]: ActiveRecord\Model::find('all', Array) #9 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Model.php(1395): call_user_func_array('static::find', Array) #10 /Users/roland/PhpstormProjects/lyra/src/routes.php(19): ActiveRecord\Model::all(Array) #11 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #12 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #13 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #14 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #15 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #16 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/App.php(476): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response)) #17 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(122): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #18 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/App.php(370): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #19 /Users/roland/PhpstormProjects/lyra/vendor/slim/slim/Slim/App.php(295): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #20 /Users/roland/PhpstormProjects/lyra/index.php(45): Slim\App->run() #21 {main}
File: /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Connection.php
Line: 251
```

**Comment by koenpunt** [comment]
This is presumably a configuration error on the remote side. The message is coming from the server and says that your ip is not allowed to connect.

**Comment by fruitloop** [comment]
Well of course the remote side does not allow me to connect if ActiveRecord tries to connect with complete bullshit login data.

According to `/vendor/php-activerecord/php-activerecord/lib/Connection.php` on Line 249
the connection should look like:

`new PDO("$info->protocol:$host;dbname=$info->db", $info->user, $info->pass, static::$PDO_OPTIONS);`

In the Stack Trace that I posted above that translates to:
`#0 /Users/roland/PhpstormProjects/lyra/vendor/php-activerecord/php-activerecord/lib/Connection.php(249): PDO->__construct('pgsql:host=e365...', NULL, 'someLongihsPass...', Array) `
the `NULL` part should definitely be `u39694db1` as my connection string looks like this:
`'production' => "pgsql://u39694db1:someLongihsPassword@e36555-pgsql.services.easyname.eu/u39694db1?charset=utf8"`

**Comment by fruitloop** [comment]
I tried that in more detail:
I created a local copy of the DB (with the same structure/data)

Now the user for the DB is in fact my local user.
When I now enter this connection String:
`pgsql://thisStinks:@localhost/u39694db1?charset=utf8`
everything works perfect, and believe me there is no user named `thisStinks` on my machine.

It therefore seems (proof is above) that ActiveRecord completely ignores the username when connecting to the DB Server. (Although it worked at some point in the past)

**Comment by koenpunt** [comment]
The fact that it worked at some point makes me believe the problem has to be in your configuration. Especially since the connection string parsing is the same for all adapters, which means that a lot of people would be experiencing this problem.

**Comment by koenpunt** [comment]
What do you get when you run the connection string through `parse_url()` yourself?

**Comment by fruitloop** [comment]
I'll try that tonight.

**Comment by fruitloop** [comment]
`parse_url()` seems to work just fine:

I tried single quotes as well as double quotes with the local string as well as the remote and it works:

```
var_dump(parse_url("pgsql://thisStinks:@localhosta/u54321db1?charset=utf8"));
array(6) {
  ["scheme"]=>
  string(5) "pgsql"
  ["host"]=>
  string(10) "localhosta"
  ["user"]=>
  string(10) "thisStinks"
  ["pass"]=>
  string(0) ""
  ["path"]=>
  string(10) "/u54321db1"
  ["query"]=>
  string(12) "charset=utf8"
}

var_dump(parse_url("pgsql://u54321db1:someLongishPassword@e1234-pgsql.services.easyname.eu/u54321db1?charset=utf8"));
array(6) {
  ["scheme"]=>
  string(5) "pgsql"
  ["host"]=>
  string(33) "e1234-pgsql.services.easyname.eu"
  ["user"]=>
  string(9) "u54321db1"
  ["pass"]=>
  string(19) "someLongishPassword"
  ["path"]=>
  string(10) "/u54321db1"
  ["query"]=>
  string(12) "charset=utf8"
}
```

Is there any chance that I created a class/variable with a name that interferes with some variables used for the connection string?
