### ISSUE TITLE
PHPActiveRecord.org being snapped?

### ISSUE THREAD

**Issue by hising** [jpfuentes2/php-activerecord#573]
I was looking for some docs and forum answers, it seems like the domain http://www.phpactiverecord.org/ is no longer owned by the project admins?

**Comment by bartveneman** [comment]
Looks like it's registered now by https://www.enom.com/. ICANN WHOIS still says @jpfuentes2, but https://www.transip.nl/whois/prm/phpactiverecord.org says if was updated today.

**Comment by israelsousa21** [comment]
Oh Jesus, have some other place with this documentário?

**Comment by SailingGoat** [comment]
Most of the documentation seems to be generated from the DocBlocks. So you
can consult the code for the comments on the function you want to use. And
you can consult Model.php for most of the functions you will be using.

**Comment by kla** [comment]
Looks like there might be an issue with the DNS. @jpfuentes2 will need to take a look at. Until then you can still reach the site at http://198.199.79.39/

**Comment by israelsousa21** [comment]
@kla Thanx a Lot, u save my life :)

**Comment by Lusitaniae** [comment]
For the meantime, I've setup http://phpactiverecord.com/ pointing to the IP referred by @kla.

**Comment by maveius** [comment]
Oh. Old documentation is very important, but I thought that it's "Big End of the ActiveRecord Era".
I'm disappointed :-( ;-P. ActiveRecord still exists :-( This site should exist forever, becouse it is very important for documentation. In my opinion ActiveRecord is Anti-Pattern and complicates a lot of things. Active Record shouldn't exists, but at work I have to using it. Eh...

**Comment by israelsousa21** [comment]
What other ORM you indicate? Redbeans?

**Comment by maveius** [comment]
Doctrine2+ is a powerfull ! :-)

**Comment by israelsousa21** [comment]
I have hear about, thanx :)

**Comment by kla** [comment]
phpactiverecord.org is working now.
