### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by adonet** [jpfuentes2/php-activerecord#594]
Website down

**Comment by fventurini** [comment]
yes ... website down!

**Comment by salvatorelapi** [comment]
Where we can get documentation ?

**Comment by mhornbacher** [comment]
Looks like it is down again 😕

**Comment by tthomasgg** [comment]
@salvatorelapi you can use cache: before the URL to access Google's cached version of the original website. 
Ps.: Tested on Chrome

**Comment by shawnpyle** [comment]
@salvatorelapi I have an older version of the site that httrack'd over a year ago because it was down shortly before then.
https://bitbucket.org/theasci/php-activerecord-site

**Comment by salvatorelapi** [comment]
Please restore documentation

**Comment by erkinsergey** [comment]
Please, this documentation is very necessary!

**Comment by jardelsantana** [comment]
We need to host it on github pages.
